apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/howard12721/mikke-api
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-migrations
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-identity-service
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-friendship-service
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-post-service
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-media-service
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-guess-service
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81
  - name: ghcr.io/howard12721/mikke-notification-service
    newTag: sha-3b6859c69d81ee86b6b7fef1fa455b83ba1f9f81

replicas:
  - name: api
    count: 3
  - name: identity-service
    count: 2
  - name: friendship-service
    count: 2
  - name: post-service
    count: 2
  - name: media-service
    count: 2
  - name: guess-service
    count: 2
  - name: notification-service
    count: 2
